### ISSUE TITLE
"Next steps with Tracing" is out of date

### ISSUE THREAD

**Issue by WesleyAC** [tokio-rs/website#757]
[Next steps with Tracing](https://tokio.rs/tokio/topics/tracing-next-steps) recommends the following:

```toml
# Implements the types defined in the Otel spec
opentelemetry = "0.17.0"
# Integration between the tracing crate and the opentelemetry crate
tracing-opentelemetry = "0.17.2" 
# Allows you to export data to Jaeger
opentelemetry-jaeger = "0.16.0"
```

However, `opentelemetry-jaeger` is deprecated and these are very old versions. This should be updated with the current best practices.
